package com.example.demo.entity;

import com.example.demo.enums.Role;
import jakarta.persistence.*;
/**

 * Class Name: User

 *

 * Purpose:

 * This entity class represents a user in the system. It is mapped to the 'users' table in the database.

 * The class includes user identification, login credentials, email, and authorization role.

 *

 * Interface Description:

 * - Provides getters and setters for all fields to support data binding and persistence operations.

 * - Designed to be used by service and repository layers for user-related operations.

 *

 * Important Data:

 * - id: unique identifier, auto-generated by the database.

 * - username: must be unique; used as login identity.

 * - password: hashed password for authentication.

 * - email: must be unique; used for user communication and verification.

 * - role: user's authorization level (e.g., ADMIN, USER).

 *

 * Development History:

 * - Designed by: Peilin Li

 * - Reviewed by: Yunyi Jiang

 * - Created on: 2025-04-27

 * - Last modified: 2025-05-01 (Initial version)

 */
@Entity
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Long id;

    @Column(name = "name", unique = true)
    private String username;

    @Column(name = "password_hash")
    private String password;

    @Column(unique = true)
    private String email;

    @Enumerated(EnumType.STRING)
    private Role role = Role.USER; // default role is USER

    // ===== Getter and Setter =====

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }
}


